from . import product_price
#from . import stock_move
#from . import work_order_hour
#from . import account_invoice
#from . import account_account
#from . import account_analytic_account
#from . import work_order_hour_tasks
#from . import hr_employee
#from . import holidays_config
#from . import res_partner
#from . import viaticos
